[project]
name = "event"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.7",
    "numpy>=2.3.5",
    "qiskit-aer>=0.17.2",
    "qiskit[visualization]>=2.2.3",
]
