[project]
name = "tarea1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.3.2",
    "scipy>=1.16.1",
    "sympy>=1.14.0",
]
